run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gosec
    - gocritic
    - revive
    - misspell

linters-settings:
  govet:
    check-shadowing: true
  revive:
    severity: warning
  gosec:
    excludes:
      - G404 # Use of weak random number generator

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
