// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Paste struct {
	ID           string           `json:"id"`
	Title        pgtype.Text      `json:"title"`
	Content      string           `json:"content"`
	Syntax       pgtype.Text      `json:"syntax"`
	IsPublic     bool             `json:"is_public"`
	IsCompressed bool             `json:"is_compressed"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type QrCode struct {
	ID        string           `json:"id"`
	Text      string           `json:"text"`
	Format    string           `json:"format"`
	Size      int32            `json:"size"`
	ImageData []byte           `json:"image_data"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type ShortUrl struct {
	ID          int64            `json:"id"`
	Code        string           `json:"code"`
	OriginalUrl string           `json:"original_url"`
	Alias       pgtype.Text      `json:"alias"`
	Clicks      int64            `json:"clicks"`
	IsPublic    bool             `json:"is_public"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Todo struct {
	ID          int64            `json:"id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	Completed   bool             `json:"completed"`
	UserID      int64            `json:"user_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type UrlClick struct {
	ID         int64            `json:"id"`
	ShortUrlID int64            `json:"short_url_id"`
	Referrer   pgtype.Text      `json:"referrer"`
	UserAgent  pgtype.Text      `json:"user_agent"`
	IpAddress  pgtype.Text      `json:"ip_address"`
	ClickedAt  pgtype.Timestamp `json:"clicked_at"`
}

type User struct {
	ID        int64            `json:"id"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
